FROM python:3.11-slim

LABEL environment="prod"
LABEL maintainer="omar"

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

ENV ENVIRONMENT=production
ENV PYTHONUNBUFFERED=1

EXPOSE 8080

CMD ["python", "app.py"]
