FROM python:3.11-slim

LABEL environment="dev"
LABEL maintainer="omar"

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

ENV ENVIRONMENT=development
ENV FLASK_ENV=development

EXPOSE 8080

CMD ["python", "app.py"]
